temperature_day_filter:
  min: 25
  consecutive_days: 3
  years: 
    start: 2018
    end: 2022
landsat_query:
  max_cloud_coverage: 10
  collections: ["landsat-c2l2-st"]
big_data_storage_path: "work/zt75vipu-master/data"
regions: ["Leipzig", "Dresden", "Hamburg"]
  