temperature_day_filter:
  min: 25
  consecutive_days: 3
  years: 
    start: 2019
    end: 2024
  max_dates_per_year: 1 # to avoid too many scenes for planet scope
landsat_query:
  max_cloud_coverage: 10
  collections: ["landsat-c2l2-st"]
osm_query:
  image_size: 5500
big_data_storage_path: "D:/master_thesis/data" #"/work/zt75vipu-thesis/data"
regions: ["Dresden", "Leipzig", "Hamburg", "Stuttgart"] # , "Leipzig", "Hamburg"  