name: genaiSpatialplan
channels:
  - anaconda
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - absl-py=2.1.0=py312h06a4308_0
  - astunparse=1.6.3=py_0
  - atk-1.0=2.36.0=ha1a6a79_0
  - blas=1.0=mkl
  - boost-cpp=1.82.0=hdb19cb5_2
  - brotli-python=1.0.9=py312h6a678d5_9
  - bzip2=1.0.8=h5eee18b_6
  - c-ares=1.19.1=h5eee18b_0
  - ca-certificates=2024.12.31=h06a4308_0
  - cairo=1.16.0=hb05425b_5
  - certifi=2024.12.14=py312h06a4308_0
  - cuda-crt-tools=12.4.131=h06a4308_0
  - cuda-cudart=12.4.127=h99ab3db_0
  - cuda-cudart_linux-64=12.4.127=hd681fbe_0
  - cuda-cupti=12.4.127=h6a678d5_1
  - cuda-nvcc-tools=12.4.131=h99ab3db_0
  - cuda-nvrtc=12.4.127=h99ab3db_1
  - cuda-nvtx=12.4.127=h6a678d5_1
  - cuda-nvvm-tools=12.4.131=h6a678d5_0
  - cuda-version=12.4=hbda6634_3
  - cudnn=9.1.1.17=cuda12_1
  - expat=2.6.4=h6a678d5_0
  - font-ttf-dejavu-sans-mono=2.37=hd3eb1b0_0
  - font-ttf-inconsolata=2.001=hcb22688_0
  - font-ttf-source-code-pro=2.030=hd3eb1b0_0
  - font-ttf-ubuntu=0.83=h8b1ccd4_0
  - fontconfig=2.14.1=h55d465d_3
  - fonts-anaconda=1=h8fa9717_0
  - fonts-conda-ecosystem=1=hd3eb1b0_0
  - freetype=2.12.1=h4a9f257_0
  - fribidi=1.0.10=h7b6447c_0
  - gdk-pixbuf=2.42.10=h5eee18b_1
  - giflib=5.2.2=h5eee18b_0
  - glib=2.78.4=h6a678d5_0
  - glib-tools=2.78.4=h6a678d5_0
  - gobject-introspection=1.78.1=py312h42194e9_1
  - google-pasta=0.2.0=pyhd3eb1b0_0
  - graphite2=1.3.14=h295c915_1
  - graphviz=2.50.0=h78213b7_2
  - gtk2=2.24.33=h73c1081_2
  - gts=0.7.6=hb67d8dd_3
  - h5py=3.12.1=py312h5842655_1
  - harfbuzz=4.3.0=hf52aaf7_2
  - hdf5=1.14.5=h2b7332f_0
  - icu=73.1=h6a678d5_0
  - intel-openmp=2023.1.0=hdb19cb5_46306
  - jpeg=9e=h5eee18b_3
  - krb5=1.20.1=h143b758_1
  - lcms2=2.16=hb9589c4_0
  - ld_impl_linux-64=2.40=h12ee557_0
  - lerc=4.0.0=h6a678d5_0
  - libabseil=20240116.2=cxx17_h6a678d5_0
  - libboost=1.82.0=h109eef0_2
  - libcublas=12.4.5.8=h99ab3db_1
  - libcufft=11.2.1.3=h99ab3db_1
  - libcurand=10.3.5.147=h99ab3db_1
  - libcurl=8.11.1=hc9e6f67_0
  - libcusolver=11.6.1.9=h99ab3db_1
  - libcusparse=12.3.1.170=h99ab3db_1
  - libdeflate=1.22=h5eee18b_0
  - libedit=3.1.20230828=h5eee18b_0
  - libev=4.33=h7f8727e_1
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=11.2.0=h1234567_1
  - libgd=2.3.3=h695aa2c_1
  - libgfortran-ng=11.2.0=h00389a5_1
  - libgfortran5=11.2.0=h1234567_1
  - libglib=2.78.4=hdc74915_0
  - libgomp=11.2.0=h1234567_1
  - libgrpc=1.62.2=h2d74bed_0
  - libiconv=1.16=h5eee18b_3
  - libnghttp2=1.57.0=h2d74bed_0
  - libnvjitlink=12.4.127=h99ab3db_1
  - libpng=1.6.39=h5eee18b_0
  - libprotobuf=4.25.3=he621ea3_0
  - librsvg=2.56.3=h056759b_0
  - libssh2=1.11.1=h251f7ec_0
  - libstdcxx-ng=11.2.0=h1234567_1
  - libtiff=4.5.1=hffd6297_1
  - libtool=2.4.6=h6a678d5_1009
  - libuuid=1.41.5=h5eee18b_0
  - libwebp=1.3.2=h11a3e52_0
  - libwebp-base=1.3.2=h5eee18b_1
  - libxcb=1.15=h7f8727e_0
  - libxml2=2.13.5=hfdd30dd_0
  - lz4-c=1.9.4=h6a678d5_1
  - mkl=2023.1.0=h213fc3f_46344
  - mkl-service=2.4.0=py312h5eee18b_2
  - mkl_fft=1.3.11=py312h5eee18b_0
  - mkl_random=1.2.8=py312h526ad5a_0
  - ml_dtypes=0.4.0=py312h526ad5a_0
  - nccl=2.21.5.1=ha515578_0
  - ncurses=6.4=h6a678d5_0
  - ninja=1.12.1=h06a4308_0
  - ninja-base=1.12.1=hdb19cb5_0
  - nspr=4.35=h6a678d5_0
  - nss=3.89.1=h6a678d5_0
  - numpy-base=1.26.4=py312h0da6c21_0
  - openjpeg=2.5.2=he7f1fd0_0
  - openssl=3.0.15=h5eee18b_0
  - opt_einsum=3.3.0=pyhd3eb1b0_1
  - packaging=24.2=py312h06a4308_0
  - pango=1.50.7=h05da053_0
  - pcre2=10.42=hebb0a14_1
  - pip=24.2=py312h06a4308_0
  - pixman=0.40.0=h7f8727e_1
  - poppler=24.09.0=hcf11d46_1
  - poppler-data=0.4.11=h06a4308_1
  - pysocks=1.7.1=py312h06a4308_0
  - python=3.12.8=h5148396_0
  - python-flatbuffers=24.3.25=py312h06a4308_0
  - re2=2022.04.01=h295c915_0
  - readline=8.2=h5eee18b_0
  - requests=2.32.3=py312h06a4308_1
  - rich=13.9.4=py312h06a4308_0
  - setuptools=75.1.0=py312h06a4308_0
  - snappy=1.2.1=h6a678d5_0
  - sqlite=3.45.3=h5eee18b_0
  - tbb=2021.8.0=hdb19cb5_0
  - tensorflow-base=2.17.0=cuda124py312hfc7ff22_200
  - tensorflow-estimator=2.17.0=cuda124py312he5efd2c_200
  - tensorflow-gpu=2.17.0=cuda124py312hd65659d_200
  - tk=8.6.14=h39e8969_0
  - typing-extensions=4.12.2=py312h06a4308_0
  - typing_extensions=4.12.2=py312h06a4308_0
  - tzdata=2024b=h04d1e81_0
  - urllib3=2.3.0=py312h06a4308_0
  - wheel=0.44.0=py312h06a4308_0
  - xz=5.4.6=h5eee18b_1
  - zlib=1.2.13=h5eee18b_1
  - zstd=1.5.6=hc292b87_0
  - pip:
    - anyio==4.8.0
    - argon2-cffi==23.1.0
    - argon2-cffi-bindings==21.2.0
    - arrow==1.3.0
    - asttokens==3.0.0
    - async-lru==2.0.4
    - attrs==24.3.0
    - babel==2.16.0
    - beautifulsoup4==4.12.3
    - bleach==6.2.0
    - cffi==1.17.1
    - charset-normalizer==3.4.1
    - comm==0.2.2
    - contourpy==1.3.1
    - cycler==0.12.1
    - debugpy==1.8.12
    - decorator==5.1.1
    - defusedxml==0.7.1
    - executing==2.1.0
    - flatbuffers==24.12.23
    - fonttools==4.55.3
    - fqdn==1.5.1
    - gast==0.6.0
    - grpcio==1.69.0
    - h11==0.14.0
    - httpcore==1.0.7
    - httpx==0.28.1
    - idna==3.10
    - ipykernel==6.29.5
    - ipython==8.31.0
    - ipywidgets==8.1.5
    - isoduration==20.11.0
    - jedi==0.19.2
    - jinja2==3.1.5
    - json5==0.10.0
    - jsonpointer==3.0.0
    - jsonschema==4.23.0
    - jsonschema-specifications==2024.10.1
    - jupyter==1.1.1
    - jupyter-client==8.6.3
    - jupyter-console==6.6.3
    - jupyter-core==5.7.2
    - jupyter-events==0.11.0
    - jupyter-lsp==2.2.5
    - jupyter-server==2.15.0
    - jupyter-server-terminals==0.5.3
    - jupyterlab==4.3.4
    - jupyterlab-pygments==0.3.0
    - jupyterlab-server==2.27.3
    - jupyterlab-widgets==3.0.13
    - keras==3.8.0
    - kiwisolver==1.4.8
    - libclang==18.1.1
    - markdown==3.7
    - markdown-it-py==3.0.0
    - markupsafe==3.0.2
    - matplotlib==3.10.0
    - matplotlib-inline==0.1.7
    - mdurl==0.1.2
    - mistune==3.1.0
    - ml-dtypes==0.4.1
    - namex==0.0.8
    - nbclient==0.10.2
    - nbconvert==7.16.5
    - nbformat==5.10.4
    - nest-asyncio==1.6.0
    - notebook==7.3.2
    - notebook-shim==0.2.4
    - numpy==2.0.2
    - opt-einsum==3.4.0
    - optree==0.14.0
    - overrides==7.7.0
    - pandocfilters==1.5.1
    - parso==0.8.4
    - pexpect==4.9.0
    - pillow==11.1.0
    - platformdirs==4.3.6
    - prometheus-client==0.21.1
    - prompt-toolkit==3.0.48
    - protobuf==5.29.3
    - psutil==6.1.1
    - ptyprocess==0.7.0
    - pure-eval==0.2.3
    - pycparser==2.22
    - pydot==3.0.4
    - pygments==2.19.1
    - pyparsing==3.2.1
    - python-dateutil==2.9.0.post0
    - python-graphviz==0.20.3
    - python-json-logger==3.2.1
    - pyyaml==6.0.2
    - pyzmq==26.2.0
    - referencing==0.36.1
    - rfc3339-validator==0.1.4
    - rfc3986-validator==0.1.1
    - rpds-py==0.22.3
    - send2trash==1.8.3
    - six==1.17.0
    - sniffio==1.3.1
    - soupsieve==2.6
    - stack-data==0.6.3
    - tensorboard==2.18.0
    - tensorboard-data-server==0.7.2
    - tensorflow==2.18.0
    - termcolor==2.5.0
    - terminado==0.18.1
    - tinycss2==1.4.0
    - tornado==6.4.2
    - traitlets==5.14.3
    - types-python-dateutil==2.9.0.20241206
    - uri-template==1.3.0
    - wcwidth==0.2.13
    - webcolors==24.11.1
    - webencodings==0.5.1
    - websocket-client==1.8.0
    - werkzeug==3.1.3
    - widgetsnbextension==4.0.13
    - wrapt==1.17.2
prefix: /home/sc.uni-leipzig.de/zt75vipu/.conda/envs/genaiSpatialplan
