name: genaiSpatialplan
channels:
  - anaconda
  - defaults
dependencies:
  - python=3.11
  - pip
  - pip:
    - python-dotenv
    - pyyaml
    - thefuzz
    - numpy
    - pandas
    - geopandas
    - polars
    - lonboard
    - pyarrow
    - geoarrow-pyarrow 
    - geoarrow-pandas
    - osmnx
    - overpass
    - matplotlib
    - mapclassify
    - seaborn
    - xarray
    - dask
    - zarr
    - rioxarray
    - rasterio
    - scikit-image
    - fiona
    - shapely
    - utm
    - leafmap
    - ipyleaflet
    - jupyter
    - boto3
    - torch
    - torchvision
    - torchaudio
    - "--extra-index-url=https://download.pytorch.org/whl/cu118"
    - torch-summary
    - einops
    - opencv-python==4.12.0.88
    
