name: genaiSpatialplan
channels:
  - anaconda
  - defaults
dependencies:
  - python=3.11
  - pip
  - pip:
    - python-dotenv
    - numpy
    - pandas
    - geopandas[complete]
    - polars
    - pyarrow
    - osmnx
    - overpass
    - matplotlib
    - mapclassify
    - seaborn
    - xarray[complete]
    - rioxarray
    - rasterio
    - scikit-image
    - fiona
    - shapely
    - leafmap
    - ipyleaflet
    - jupyter[complete]
    - boto3
    
