name: pytorch-env
channels:
  - pytorch
  - nvidia
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - blas=1.0=mkl
  - brotli-python=1.0.9=py311h6a678d5_9
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2024.12.31=h06a4308_0
  - certifi=2024.12.14=py311h06a4308_0
  - charset-normalizer=3.3.2=pyhd3eb1b0_0
  - cuda-cudart=11.8.89=0
  - cuda-cupti=11.8.87=0
  - cuda-libraries=11.8.0=0
  - cuda-nvrtc=11.8.89=0
  - cuda-nvtx=11.8.86=0
  - cuda-runtime=11.8.0=0
  - cuda-version=12.8=3
  - ffmpeg=4.3=hf484d3e_0
  - filelock=3.13.1=py311h06a4308_0
  - freetype=2.12.1=h4a9f257_0
  - giflib=5.2.2=h5eee18b_0
  - gmp=6.2.1=h295c915_3
  - gmpy2=2.1.2=py311hc9b5ff0_0
  - gnutls=3.6.15=he1e5248_0
  - idna=3.7=py311h06a4308_0
  - intel-openmp=2023.1.0=hdb19cb5_46306
  - jinja2=3.1.4=py311h06a4308_1
  - jpeg=9e=h5eee18b_3
  - lame=3.100=h7b6447c_0
  - lcms2=2.16=hb9589c4_0
  - ld_impl_linux-64=2.40=h12ee557_0
  - lerc=4.0.0=h6a678d5_0
  - libcublas=11.11.3.6=0
  - libcufft=10.9.0.58=0
  - libcufile=1.13.0.11=0
  - libcurand=10.3.9.55=0
  - libcusolver=11.4.1.48=0
  - libcusparse=11.7.5.86=0
  - libdeflate=1.22=h5eee18b_0
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libiconv=1.16=h5eee18b_3
  - libidn2=2.3.4=h5eee18b_0
  - libjpeg-turbo=2.0.0=h9bf148f_0
  - libnpp=11.8.0.86=0
  - libnvjpeg=11.9.0.86=0
  - libpng=1.6.39=h5eee18b_0
  - libstdcxx-ng=11.2.0=h1234567_1
  - libtasn1=4.19.0=h5eee18b_0
  - libtiff=4.5.1=hffd6297_1
  - libunistring=0.9.10=h27cfd23_0
  - libuuid=1.41.5=h5eee18b_0
  - libwebp=1.3.2=h11a3e52_0
  - libwebp-base=1.3.2=h5eee18b_1
  - llvm-openmp=14.0.6=h9e868ea_0
  - lz4-c=1.9.4=h6a678d5_1
  - markupsafe=2.1.3=py311h5eee18b_1
  - mkl=2023.1.0=h213fc3f_46344
  - mkl-service=2.4.0=py311h5eee18b_2
  - mkl_fft=1.3.11=py311h5eee18b_0
  - mkl_random=1.2.8=py311ha02d727_0
  - mpc=1.1.0=h10f8cd9_1
  - mpfr=4.0.2=hb69a4c5_1
  - mpmath=1.3.0=py311h06a4308_0
  - ncurses=6.4=h6a678d5_0
  - nettle=3.7.3=hbbd107a_1
  - networkx=3.4.2=py311h06a4308_0
  - numpy=2.0.1=py311h08b1b3b_1
  - numpy-base=2.0.1=py311hf175353_1
  - openh264=2.1.1=h4ff587b_0
  - openjpeg=2.5.2=he7f1fd0_0
  - openssl=3.0.15=h5eee18b_0
  - pillow=11.0.0=py311hcea889d_1
  - pip=24.2=py311h06a4308_0
  - pysocks=1.7.1=py311h06a4308_0
  - python=3.11.11=he870216_0
  - pytorch=2.5.1=py3.11_cuda11.8_cudnn9.1.0_0
  - pytorch-cuda=11.8=h7e8668a_6
  - pytorch-mutex=1.0=cuda
  - pyyaml=6.0.2=py311h5eee18b_0
  - readline=8.2=h5eee18b_0
  - requests=2.32.3=py311h06a4308_1
  - setuptools=75.1.0=py311h06a4308_0
  - sqlite=3.45.3=h5eee18b_0
  - sympy=1.13.3=py311h06a4308_0
  - tbb=2021.8.0=hdb19cb5_0
  - tk=8.6.14=h39e8969_0
  - torchtriton=3.1.0=py311
  - torchvision=0.20.1=py311_cu118
  - typing_extensions=4.12.2=py311h06a4308_0
  - urllib3=2.3.0=py311h06a4308_0
  - wheel=0.44.0=py311h06a4308_0
  - xz=5.4.6=h5eee18b_1
  - yaml=0.2.5=h7b6447c_0
  - zlib=1.2.13=h5eee18b_1
  - zstd=1.5.6=hc292b87_0
  - pip:
    - anyio==4.8.0
    - argon2-cffi==23.1.0
    - argon2-cffi-bindings==21.2.0
    - arrow==1.3.0
    - asttokens==3.0.0
    - async-lru==2.0.4
    - attrs==24.3.0
    - babel==2.16.0
    - beautifulsoup4==4.12.3
    - bleach==6.2.0
    - cffi==1.17.1
    - comm==0.2.2
    - contourpy==1.3.1
    - cycler==0.12.1
    - debugpy==1.8.12
    - decorator==5.1.1
    - defusedxml==0.7.1
    - executing==2.2.0
    - fastjsonschema==2.21.1
    - fonttools==4.55.5
    - fqdn==1.5.1
    - h11==0.14.0
    - httpcore==1.0.7
    - httpx==0.28.1
    - ipykernel==6.29.5
    - ipython==8.31.0
    - ipywidgets==8.1.5
    - isoduration==20.11.0
    - jedi==0.19.2
    - json5==0.10.0
    - jsonpointer==3.0.0
    - jsonschema==4.23.0
    - jsonschema-specifications==2024.10.1
    - jupyter==1.1.1
    - jupyter-client==8.6.3
    - jupyter-console==6.6.3
    - jupyter-core==5.7.2
    - jupyter-events==0.11.0
    - jupyter-lsp==2.2.5
    - jupyter-server==2.15.0
    - jupyter-server-terminals==0.5.3
    - jupyterlab==4.3.4
    - jupyterlab-pygments==0.3.0
    - jupyterlab-server==2.27.3
    - jupyterlab-widgets==3.0.13
    - kiwisolver==1.4.8
    - matplotlib==3.10.0
    - matplotlib-inline==0.1.7
    - mistune==3.1.0
    - nbclient==0.10.2
    - nbconvert==7.16.5
    - nbformat==5.10.4
    - nest-asyncio==1.6.0
    - notebook==7.3.2
    - notebook-shim==0.2.4
    - overrides==7.7.0
    - packaging==24.2
    - pandas==2.2.3
    - pandocfilters==1.5.1
    - parso==0.8.4
    - pexpect==4.9.0
    - platformdirs==4.3.6
    - prometheus-client==0.21.1
    - prompt-toolkit==3.0.50
    - psutil==6.1.1
    - ptyprocess==0.7.0
    - pure-eval==0.2.3
    - pycparser==2.22
    - pygments==2.19.1
    - pyparsing==3.2.1
    - python-dateutil==2.9.0.post0
    - python-json-logger==3.2.1
    - pytz==2024.2
    - pyzmq==26.2.0
    - referencing==0.36.1
    - rfc3339-validator==0.1.4
    - rfc3986-validator==0.1.1
    - rpds-py==0.22.3
    - send2trash==1.8.3
    - six==1.17.0
    - sniffio==1.3.1
    - soupsieve==2.6
    - stack-data==0.6.3
    - terminado==0.18.1
    - tinycss2==1.4.0
    - torchsummary==1.5.1
    - tornado==6.4.2
    - traitlets==5.14.3
    - types-python-dateutil==2.9.0.20241206
    - tzdata==2025.1
    - uri-template==1.3.0
    - wcwidth==0.2.13
    - webcolors==24.11.1
    - webencodings==0.5.1
    - websocket-client==1.8.0
    - widgetsnbextension==4.0.13
prefix: /home/sc.uni-leipzig.de/zt75vipu/.conda/envs/pytorch-env
